jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run migrations
        run: dotnet ef database update

      - name: Pause and debug
        uses: mxschmitt/action-tmate@v3
