name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Your_password123
        ports:
          - 1433:1433

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install EF Core Tools
        run: |
          dotnet tool install --global dotnet-ef
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Ждем запуска SQL Server
      - name: Wait for SQL Server
        run: |
          sleep 20

      - name: Run migrations
        run: dotnet ef database update --verbose
        env:
          ConnectionStrings__DefaultConnection: >
            Server=localhost,1433;
            Database=EntityNexusDb;
            User Id=sa;
            Password=Your_password123;
            TrustServerCertificate=True;

      - name: Test
        run: dotnet test --no-build --configuration Release
