# .github/workflows/debug.yml

name: Debug SQL + Tmate

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Your_password123
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' -C"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run migrations
        run: dotnet ef database update
        env:
          ConnectionStrings__DefaultConnection: >
            Server=localhost,1433;
            Database=EntityNexusDb;
            User Id=sa;
            Password=Your_password123;
            TrustServerCertificate=True;

      - name: Show containers
        run: docker ps -a

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
          echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      - name: Test SQL connection
        run: |
          sqlcmd -S localhost,1433 \
                 -U sa \
                 -P Your_password123 \
                 -C \
                 -Q "SELECT name FROM sys.databases"

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
